### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by spinningarrow** [sourcejs/sourcejs-contrib-dss#2]
I must be missing some step in the documentation or something, but I followed everything it said and I still don't see any generated stuff in my spec. How can I debug this?

**Comment by spinningarrow** [comment]
Never mind, I accidentally installed the plugin in the root folder instead of `user`. Whoops!

**Comment by robhrt7** [comment]
No worries, feel free to ask any questions here. 

In 0.6.0, as SourceJS official install path will be done only through NPM, there will be no confusion with nested folder, since you'll have only `user` as root and SourceJS as a dependency in `node_modules`. You can also try it out now, following this install instructions https://sourcejs.com/docs/base/#from-npm.

**Comment by spinningarrow** [comment]
That's great - it'll definitely help avoid some confusion. I'll check it out 😀
Btw we created a fork of this that supports KSS, take a look if you're interested! https://github.com/xevenheaven/sourcejs-kss

**Comment by robhrt7** [comment]
@spinningarrow that's really cool! thanks for you're commitment to the community! 

Could you also add PR to our demo project, to place plugin on sourcejs.com? Here's the repo https://github.com/sourcejs/example-specs-showcase which holds this catalog https://sourcejs.com/specs/example-specs-showcase/
